# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f7509b9330561340739848b213de19025b62b0e0acc1f7d00104253547bf8be61351a5e9389b6ddeabe52f6a512a009cca33018a8bee8d71fe5359be23671ff

test:
  secret_key_base: 1f83a28c3590c99663c7d86709da55a1010d0971cc9a43b1beb311e6890f23ca114af5567fd8ce2a499f3c7028cef91fdd79c1aec430b9b2f38ce6d2c4cfdad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
